vuelessjs/vueless

.storybook/preview.js
src/ui.button-link/configs/default.config.js
src/ui.button-link/index.vue
src/ui.form-input-file/index.vue
src/ui.form-input-search/index.vue
src/ui.text-alert/index.vue
src/ui.text-block/index.vue

https://ilevel.atlassian.net/browse/FN-1830
- Fixed ULink storybook page.
- Added `<router-link>` props to `<ULink>`

Fn 1830 add router link props to u link dmytro holdobin

---

src/directive.clickOutside/index.js
src/directive.tooltip/index.js
src/ui.dropdown-badge/index.vue
src/ui.dropdown-button/index.vue
src/ui.dropdown-link/index.vue

- Added onClickOutside directive
- Fixed issue with dropdown item click not being triggered
https://ilevel.atlassian.net/jira/software/c/projects/FN/boards/2?selectedIssue=FN-1828

F1828_Fixed-issue-when-dropdown-item-click-wasnt-triggered_Dmytro_Holdobin

---

src/composable.adjustElementPosition/index.js
src/ui.form-date-picker-range/composables/attrs.composable.js
src/ui.form-date-picker-range/configs/default.config.js
src/ui.form-date-picker-range/index.stories.js
src/ui.form-date-picker-range/index.vue
src/ui.form-date-picker/composables/attrs.composable.js
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.stories.js
src/ui.form-date-picker/index.vue

- Added adjustElementPosition composable to position element relatively to another element
- Added auto position for datepickers calendar
- Added props for datepickers to set position of calendar
- Updated datepickers stories
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-11

VL-11_Add-auto-position-for-datepicers-calendar_Dmytro-Holdobin

---

src/ui.data-table/components/TableRow.vue
src/ui.data-table/composables/attrs.composable.js
src/ui.data-table/configs/default.config.js
src/ui.data-table/index.stories.js
src/ui.data-table/index.vue
src/ui.data-table/services/table.service.js

- Moved action and sticky table headers to separate component.
- Rewritten table nesting logic and updated related storybook stories.
Put the following row structure in the table to make it nested row:
```
{
id: 1,
isChecked: false,
key_1: {
primary: "primary",
secondary: "secondary",
},
key_2: {
primary: "primary",
secondary: "secondary",
},
key_3: {
primary: "primary",
secondary: "secondary",
},
key_4: {
primary: "primary",
secondary: "secondary",
},
row: {
id: 2
...
row: {
id: 3
...
}
}
}
```

VL-9_Rewrite-table-nesting-logic_Dmytro_Holdobin

---

src/composable.ui/index.js
src/ui.button-toggle-item/index.vue
src/ui.data-table/components/TableRow.vue
src/ui.dropdown-badge/index.vue
src/ui.dropdown-button/index.stories.js
src/ui.dropdown-button/index.vue
src/ui.dropdown-link/index.vue
src/ui.dropdown-list/index.vue

Events are attributes too, and our composable used attributed from root element to every child element, in result we had root events on every other element.
>https://ilevel.atlassian.net/browse/VL-27

VL-27_Fix-button-double-event_Dmytro-Holdobin

---

src/ui.form-date-picker-range/configs/default.config.js
src/ui.form-date-picker-range/index.vue

- Used UButton component in datepickerRanage
> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-16

VL-16_Refactor-datepicker-range_Dmytro-Holdobin

---

src/ui.form-calendar/configs/default.config.js
src/ui.form-calendar/index.stories.js
src/ui.form-calendar/index.vue
src/ui.form-date-picker-range/index.stories.js
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.stories.js
src/ui.form-date-picker/index.vue

Added timeFormat for datepicker and calendar components to be used insted of dateFormat when timepicker is enabled

VL_Add-time-format-for-datepicker_Dmytro-Holdobin

---

src/composable.mutationObserver/index.js
src/ui.data-table/components/TableRow.vue

- Added dynamic title for table cells witch applied when cell is overflown.
- Added mutationObserver composable.
Change content of table item (onClick on with setTimeout) to test it. Unfortunately it doesn't work when you edit content directly in devtools.
> https://ilevel.atlassian.net/browse/VL-83

VL-83_Dynamic-title-for-table-cells_Dmytro-Holdobin

---

src/ui.dropdown-badge/UDropdownBadge.vue
src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-link/UDropdownLink.vue
src/ui.dropdown-list/UDropdownList.vue

Dropdown components are not selects, they can't have initial value and should not remember last clicked element, so it's strange that those elements have event named `select` and some internal model value which is not required.
- Removed internal model values from dropdown components.
- Added clickOption event to dropdown components and DropdownList component.

VL_Replace-select-event-with-click-event-in-dropdown-components_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

- Fix getRowAttrs function (you need to add `.value` for each returned Attrs via v-bind function to apply them correctly to a tr element)
- Add `contentClasses` property check to apply classes either for `td` itself, or on content div instead

VL_UTable-bugs-fix_Vitalii-Dudnik

---

src/directives/vTooltip.js

- Added override for overload which accept only content string.
- Disabled tooltip when content it falsy value.
> https://ilevel.atlassian.net/browse/VL-112

VL-112_V-tooltip-improvments_Dmtyro-Holdobin

---

src/ui.data-table/UTableRow.vue

Hidden toggle visiblity icon when nested row is empty

VL_Hide-toggle-visiblity-icon-when-nested-row-is-empty_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue

Fix cell value bug (if value is an empty object - empty curly braces
are displayed instead of hyphen symbol)

VL_UTable-nested-row-value-fix_Vitalii-Dudnik

---

.storybook/preview.js
src/composables/useDarkMode.ts
src/constants.js
src/types.ts
src/utils/theme.ts
vueless.config.ts

- Fixed storybook color theme switch.
- Removed logic related to caching color scheme and switching it according to browser's settings. It should be up to the user to decide whether they want to track browser's theme, make theme static, cache it and under which key. 
> https://ilevel.atlassian.net/browse/VL-147

VL-147_Fix-dark-mode-story-book-switch_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts
src/ui.data-table/useAttrs.ts

For more flexability removed <td /> wrappers of "before-header" and "after-last-row"  slots.

VL_Remove-td-slot-wrappers_Dmytro-Holdobin

---

src/constants.js
src/plugin-vite.js
src/utils/node/dynamicProps.js
src/utils/node/dynamicStories.js

Added option to hide storybook story for component
> https://ilevel.atlassian.net/browse/VL-169

VL-169_Add-hide-story-option-to-config_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue

Add computed property to check if nestedData.rows exists and its length is more than zero, so that toggle icon is only displayed when nested content is present

VL_UTable-toggle-nestedData-fix_Vitalii-Dudnik

---

src/utils/node/loaderIcon.js

Fix icon loader bug, when after the first element of array does not match - the function exits immediately.
Instead of "return", "continue" is needed for correct icon parsing

VL_IconLoader-fix_Vitalii-Dudnik

---

src/ui.loader-progress/ULoaderProgress.vue
src/ui.loader-progress/useLoaderProgress.ts

- Refactored code.
- Fixed issue when props of one loader controlled others.
- Controller functions can't stop loader enabled by props now.

VL_Change-loader-progress-logic_Dmytro-Holdobin

---

src/ui.form-input/storybook/stories.ts

Update UInput component stories

VL-133_UInput-stories-refinement

---

src/ui.form-select/config.ts

Fixed issue when select's before and after slot items were disabled with props

VL_Fix-select-slot-disabled-state_Dmytro-Holdobin

---

src/ui.form-input-money/UInputMoney.vue
src/ui.form-input-money/storybook/stories.ts
src/ui.form-input-number/storybook/stories.ts
src/ui.form-input-rating/UInputRating.vue
src/ui.form-input-rating/config.ts
src/ui.form-input-rating/storybook/stories.ts
src/ui.form-input-rating/types.ts
src/ui.form-input-search/UInputSearch.vue
src/ui.form-input-search/config.ts
src/ui.form-input-search/storybook/stories.ts
src/ui.form-input-search/types.ts
src/ui.form-input/UInput.vue
src/ui.form-input/storybook/stories.ts
src/ui.form-input/types.ts

- Update stories for UInputMoney & UInputSearch, adjust stories of UInput component
- Refine UInputRating component's stories

VL-133_Input-group-stories-refinement_Vitalii-Dudnik

---

src/ui.loader-progress/ULoaderProgress.vue
src/ui.loader-progress/config.ts
src/ui.loader-progress/constants.ts
src/ui.loader-progress/storybook/docs.mdx
src/ui.loader-progress/storybook/stories.ts
src/ui.loader-progress/types.ts
src/ui.loader-progress/useLoaderProgress.ts

- Removed addRequestUrl and removeRequestUrl because of they implement the same logic as loaderProgressOn and loaderProgressOff.
- Removed isLoading reactive variable because of it is not clear which loader is loading.
- Added option to pass "any" resource to run loader on every time when global resource queue changes.
- Removed redundant code and refactored the rest.
- Exposed following loader properties and methods: start, stop, isLoading.
- Changed docs accordingly to changes above.

VL_Fix-and-refactor-loader_Dmytro-Holdobin

---

src/ui.form-select/config.ts

Adjust afterToggle config key padding-top for correct layout at different sizes and label align
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-198

VL-198_USelect-afterToggle-padding-fix_Vitalii-Dudnik

---

src/ui.form-label/storybook/stories.ts

Adjust ULabel "align" prop variants, so that "topInside" is not shown in the storybook to prevent incorrect layout (this variant is used specifically for inputs).

VL_ULabel-argTypes-adjustment_Vitalii-Dudnik

---

src/ui.form-radio/URadio.vue

- Fixed issue when initial modelValue of radioGroup were not applied to radio element.
- Fixed issue when radio element emitted value on initial render when initial modelValue was set to null, undefined or empty string.

VL_Fix-radio-inital-modelValue-update-issue_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue

fix(USelect): improve click event handling and propagation
- Add missing 'click' event to emit definitions
- Emit click events on wrapper and label interactions
- Remove .stop modifiers to allow proper event bubbling
- Ensure click events are properly propagated to parent components
This fixes issues where click events were being prevented from bubbling up to parent components that needed to handle select interactions.

VL_Fix-select-click-event_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue

Refactored `USelect` component: renamed `remove` event to `removeOption` for clarity and added `clear` event to handle select clearing.
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-256

VL-256_USelect-add-clear-event_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/tests/UTable.test.ts
src/ui.data-table/tests/UTableRow.test.ts

feat: enhance UTable component with immediate watchers for expandedRows prop
- Updated UTable.vue to add an immediate watcher for expandedRows prop.
- Expanded unit tests for UTable to cover various scenarios, including column rendering, row selection, and expanded rows.
- Introduced a new UTableRow.test.ts file to thoroughly test UTableRow component functionality, including props, events, and slots.
- Added tests for dynamic classes, empty cell labels, and nested row handling.
- Improved test coverage for events such as row clicks, checkbox toggles, and expand/collapse actions.

VL-252_Add-UTable-tests_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue

Refactor date range validation in `UCalendar.vue`
Update `isOutOfRange` logic to ensure it only checks when `parsedDate` is not null.

VL_UCalendar-fix-isOutOfRange-check_Vitalii-Dudnik

---

src/ui.container-accordion-item/UAccordionItem.vue
src/ui.container-accordion-item/tests/UAccordionItem.test.ts
src/ui.container-accordion/tests/UAccordion.test.ts

Fix UAccordionItem `onClickItem` collapse logic:
- Accordion item is now collapsed only when its title is clicked (instead of checking description/content blocks with possible nested elements like dropdowns, that caused accordion to collapse)

VL_UAccordionItem-click-event-fix_Vitalii-Dudnik
