.storybook/preview.js

Fixed invalid path to store module in storybook's preview.js file

Fix invalid path in sotorybook

---

src/ui.data-table/index.stories.js

https://ilevel.atlassian.net/browse/FN-1780

Add stories for table comoponent

---

package-lock.json
package.json
src/directive.tooltip/index.js
src/ui.image-icon/index.vue
vueless.config.js

- Removed vue-tippy package
- Added tippy.js package
- Implemented v-tooltip directive
https://ilevel.atlassian.net/jira/software/c/projects/FN/boards/2?selectedIssue=FN-1824

Add v-tooltip directive

---

src/adatper.locale/vueless.js
src/index.js

- Added useLocale export from index.js
- Added internal merge with default english locale
- Renamed locale key to i18n

Add default locale internal merge

---

src/ui.container-page/index.vue
src/ui.loader-rendering/composables/attrs.composable.js
src/ui.loader-rendering/configs/default.config.js
src/ui.loader-rendering/constants/index.js
src/ui.loader-rendering/index.vue
src/ui.loader/index.vue

https://ilevel.atlassian.net/browse/FN-1827

Moved loader rendering component to vueless architecture

---

src/ui.form-date-picker-range/composables/attrs.composable.js
src/ui.form-date-picker-range/configs/default.config.js
src/ui.form-date-picker-range/constants/index.js
src/ui.form-date-picker-range/index.vue

Details:
- Added a new prop dateFormat for easier customization of the date format in the component.
- Included the feature periodButtonIconAttrs for a cool update of the period button icon.
- Dropped the constant RANGE_INPUT_FORMAT, which is no longer being used in the code.

Change: Added new props and feature in the UDatePickerRange component.

---

src/ui.progress/composables/attrs.composable.js
src/ui.progress/configs/default.config.js
src/ui.progress/constants/index.js
src/ui.progress/index.stories.js
src/ui.progress/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/WHMCS/boards/10?selectedIssue=WHMCS-10

Added-progress-component

---

src/ui.form-input-file/configs/default.config.js

https://ilevel.atlassian.net/jira/software/c/projects/WHMCS/boards/10?selectedIssue=WHMCS-11

WHMCS-11_Correct-InputFile-styles_Dmytro_Holdobin

---

src/ui.data-table/configs/default.config.js

https://ilevel.atlassian.net/jira/software/c/projects/PINE/boards/9?selectedIssue=PINE-7

PINE-7_Remove-text-wrap-in-table-headers_Dmytro_Holdobin

---

src/ui.button-link/configs/default.config.js

Fixed button link safelist variant

FN-1828_Fix-link-safelist_Dmytro-Holdobin

---

src/ui.dropdown-link/configs/default.config.js

- Fixed dropdown icon rotate issue

FN-1828_Fix-dropdown-icon-rotate-issue_Dmytro-Holdobin

---

src/ui.form-date-picker-range/composables/attrs.composable.js
src/ui.form-date-picker-range/configs/default.config.js
src/ui.form-date-picker-range/constants/index.js
src/ui.form-date-picker-range/index.stories.js
src/ui.form-date-picker-range/index.vue
src/ui.form-date-picker-range/services/dateRange.service.js
src/ui.form-date-picker/composables/attrs.composable.js
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.stories.js
src/ui.form-date-picker/index.vue

- Fixed bugs listed in the task
- Added openDirection props to datepicker component to control calendar placement
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-11

VL-11_Fix-datepicker-range-bugs_Dmytro-Holdobin

---

src/ui.form-input-file/composables/attrs.composable.js
src/ui.form-input-file/configs/default.config.js
src/ui.form-input-file/index.stories.js
src/ui.form-input-file/index.vue
src/ui.text-alert/configs/default.config.js
src/ui.text-file/composables/attrs.composable.js
src/ui.text-file/configs/default.config.js
src/ui.text-file/constants/index.js
src/ui.text-file/index.vue
src/ui.text-files/composables/attrs.composable.js
src/ui.text-files/configs/default.config.js
src/ui.text-files/index.stories.js
src/ui.text-files/index.vue

- Completed file input component
- Refactored and changed other components related to files
- Added sizes props to all file components
- Now UFiles is hight level component where you can just pass array of File objects

VL-1_Complete-file-input-component_Dmytro-Holdobin

---

src/ui.form-input-file/configs/default.config.js
src/ui.form-input-file/index.stories.js

- Fixed input file slot placement
https://ilevel.atlassian.net/browse/VL-13

VL-13_Fix-input-file-slot-placement_Dmytro_Holdobin

---

src/ui.button/index.stories.js
src/ui.button/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/FN/boards/2?selectedIssue=FN-1845

FN-1845_UButton-icons_Vitalii-Dudnik

---

src/ui.form-date-picker-range/index.vue
src/ui.loader-top/Docs.mdx
src/ui.loader-top/composables/useLoaderTop.js
src/ui.loader-top/index.vue
src/ui.loader-top/services/loaderTop.service.js

- Removed redundant functions and logic from loader top.
- Fixed loader top

VL-4_Fix-loader-top_Dmytro_Holdobin

---

src/ui.navigation-progress/composables/attrs.composable.js
src/ui.navigation-progress/configs/default.config.js
src/ui.navigation-progress/index.stories.js
src/ui.navigation-progress/index.vue

- Added indicator props and slot
- Added option to pass array into max props to show steps below. You can access them via scoped slot
- Added stories for props
> https://ilevel.atlassian.net/browse/VL-2

VL-2_UProgress-add-new-props_Dmytro_Holdobin

---

src/ui.form-calendar/components/DayView.vue
src/ui.form-calendar/components/MonthView.vue
src/ui.form-calendar/components/YearView.vue
src/ui.form-calendar/composables/attrs.composable.js
src/ui.form-calendar/configs/default.config.js
src/ui.form-calendar/index.vue
src/ui.form-date-picker/index.vue

- Renamed config keys
- General refactoring

VL-15_Calendar-refactoring_Dmytro_Holdobin

---

src/ui.form-input/index.stories.js
src/ui.form-input/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/FN/boards/2?selectedIssue=FN-1845

FN-1845_UInput-icons_Vitalii-Dudnik

---

src/ui.button/index.vue
src/ui.dropdown-badge/index.vue
src/ui.dropdown-button/index.vue
src/ui.dropdown-link/index.vue
src/ui.form-checkbox-group/index.stories.js
src/ui.form-checkbox-group/index.vue
src/ui.form-checkbox/composables/attrs.composable.js
src/ui.form-checkbox/index.vue
src/ui.form-radio-group/Docs.mdx
src/ui.form-radio-group/configs/default.config.js
src/ui.form-radio-group/index.stories.js
src/ui.form-radio-group/index.vue
src/ui.form-radio/configs/default.config.js
src/ui.form-radio/index.vue
src/ui.text-alert/configs/default.config.js

- Refactored radio group and checkbox group components.
- Fixed provide and inject between options, slots and group component
- Added stories to storybook
> https://ilevel.atlassian.net/browse/VL-17

VL-17_Groups-refactoring_Dmytro_Holdobin

---

src/ui.loader-rendering/composables/attrs.composable.js
src/ui.loader/composables/attrs.composable.js
src/ui.loader/configs/default.config.js
src/ui.loader/index.vue

Added disabled props for ULoader component
- Added disabled props.
- Added related stories.
> https://ilevel.atlassian.net/browse/VL-21

VL-21_Add-disabled-props-for-loader-component_Dmytro-Holdobin

---

src/ui.text-alert/composables/attrs.composable.js
src/ui.text-alert/configs/default.config.js
src/ui.text-alert/index.vue
src/ui.text-badge/composables/attrs.composable.js
src/ui.text-badge/index.stories.js
src/ui.text-badge/index.vue
src/ui.text-block/composables/attrs.composable.js
src/ui.text-block/index.vue
src/ui.text-empty/composables/attrs.composable.js
src/ui.text-empty/configs/default.config.js
src/ui.text-empty/index.stories.js
src/ui.text-empty/index.vue
src/ui.text-header/composables/attrs.composable.js
src/ui.text-header/index.stories.js
src/ui.text-header/index.vue
src/ui.text-money/composables/attrs.composable.js
src/ui.text-money/index.stories.js

VL-25_Text-new-composables_Vitalii-Dudnik

---

src/ui.text-file/composables/attrs.composable.js
src/ui.text-file/configs/default.config.js
src/ui.text-file/index.vue
src/ui.text-files/composables/attrs.composable.js
src/ui.text-files/configs/default.config.js
src/ui.text-files/index.vue
src/ui.text-notify/composables/attrs.composable.js
src/ui.text-notify/index.vue

VL-25_Content-new-composables_Vitalii-Dudnik

---

src/ui.loader/index.stories.js

https://ilevel.atlassian.net/browse/VL-21

VL-21_Add-loader-loading-props_Dmytro-Holdobin

---

src/ui.image-avatar/composables/attrs.composable.js
src/ui.image-avatar/configs/default.config.js
src/ui.image-avatar/index.vue
src/ui.image-icon/composables/attrs.composable.js
src/ui.image-icon/index.vue

VL-25_Images-&-icons-new-composables_Vitalii-Dudnik

---

src/ui.loader-rendering/composables/attrs.composable.js
src/ui.loader-rendering/configs/default.config.js
src/ui.loader-rendering/index.vue
src/ui.loader-top/composables/attrs.composable.js
src/ui.loader-top/index.vue
src/ui.loader/composables/attrs.composable.js
src/ui.loader/index.vue
src/ui.other-dot/composables/attrs.composable.js
src/ui.other-dot/index.vue

VL-25_Loaders-&-dot-new-composables_Vitalii-Dudnik

---

src/ui.form-checkbox-group/composables/attrs.composable.js
src/ui.form-checkbox-group/configs/default.config.js
src/ui.form-checkbox-group/index.vue
src/ui.form-checkbox-multi-state/composables/attrs.composable.js
src/ui.form-checkbox-multi-state/configs/default.config.js
src/ui.form-checkbox-multi-state/index.vue
src/ui.form-checkbox/composables/attrs.composable.js
src/ui.form-checkbox/configs/default.config.js
src/ui.form-checkbox/index.stories.js
src/ui.form-checkbox/index.vue
src/ui.form-switch/composables/attrs.composable.js
src/ui.form-switch/configs/default.config.js
src/ui.form-switch/index.vue

VL-25_Checkbox-new-composables_Vitalii-Dudnik

---

src/ui.form-input-file/composables/attrs.composable.js
src/ui.form-input-file/configs/default.config.js
src/ui.form-input-file/index.vue
src/ui.form-input-money/composables/attrs.composable.js
src/ui.form-input-money/configs/default.config.js
src/ui.form-input-money/index.stories.js
src/ui.form-input-number/composables/attrs.composable.js
src/ui.form-input-number/configs/default.config.js
src/ui.form-input-number/index.vue
src/ui.form-input-rating/composables/attrs.composable.js
src/ui.form-input-rating/index.vue
src/ui.form-input-search/composables/attrs.composable.js
src/ui.form-input-search/configs/default.config.js
src/ui.form-input-search/index.stories.js
src/ui.form-input-search/index.vue
src/ui.form-textarea/composables/attrs.composable.js
src/ui.form-textarea/configs/default.config.js
src/ui.form-textarea/index.stories.js
src/ui.form-textarea/index.vue

VL-25_Inputs-new-composables_Vitalii-Dudnik

---

src/ui.form-label/composables/attrs.composable.js
src/ui.form-label/index.vue
src/ui.form-radio-group/composables/attrs.composable.js
src/ui.form-radio-group/configs/default.config.js
src/ui.form-radio-group/index.vue
src/ui.form-radio/composables/attrs.composable.js
src/ui.form-radio/configs/default.config.js
src/ui.form-radio/index.stories.js
src/ui.form-radio/index.vue

VL-25_Radio-new-composables_Vitalii-Dudnik

---

package-lock.json
package.json

Update vueless version from 0.0.211 to 0.0.212 (current)

VL_Version-update_Vitalii-Dudnik

---

src/ui.form-input-file/configs/default.config.js

Added align-self center for UInput placeholder
>https://ilevel.atlassian.net/browse/VL-1

VL-1_Center-Uinput-placeholder-in-multiple-mode_Dmytro-Holdobin

---

src/ui.text-block/index.stories.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-33

VL-33_UText-new-style-less-architecture_Vitalii-Dudnik

---

src/ui.button-toggle-item/composables/attrs.composable.js
src/ui.button-toggle-item/configs/default.config.js
src/ui.button-toggle-item/index.vue
src/ui.button-toggle/index.stories.js
src/ui.button-toggle/index.vue

- Fixed multiple selection
- Renamed provide/inject values
- Added stories and fixed warnings
> https://ilevel.atlassian.net/browse/VL-26

UToggle bug fixes and refactoring

---

src/composable.ui/index.js
src/ui.button-toggle-item/composables/attrs.composable.js
src/ui.button-toggle-item/configs/default.config.js
src/ui.button-toggle-item/index.vue
src/ui.button-toggle/configs/default.config.js
src/ui.button-toggle/index.stories.js
src/ui.button-toggle/index.vue
src/ui.form-calendar/composables/attrs.composable.js
src/ui.form-date-picker/composables/attrs.composable.js
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.vue
src/ui.form-input-search/configs/default.config.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-45

VL-45_Add-component-key-into-all-configs_Vitalii-Dudnik

---

src/ui.form-label/configs/default.config.js
src/ui.form-label/index.stories.js
src/ui.form-label/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-19

VL-19_ULabel-stories_Vitalii-Dudnik

---

src/ui.data-table/composables/attrs.composable.js

VL_Fix-table-styles_Dmytro-holdobin

---

src/ui.navigation-progress/components/StepperProgress.vue
src/ui.navigation-progress/index.vue

- Used UHeader component in progress stepper. 
- First step is now zero
> https://ilevel.atlassian.net/browse/VL-2

VL-2_Use-Header-in-stepper_Dmytro-holdobin

---

package-lock.json
src/composable.adjustElementPosition/index.js
src/composable.autoPosition/index.js
src/ui.form-date-picker-range/composables/attrs.composable.js
src/ui.form-date-picker-range/index.stories.js
src/ui.form-date-picker-range/index.vue
src/ui.form-date-picker/composables/attrs.composable.js
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.vue
src/ui.form-input/index.stories.js

- Fixed datepickers label align.
- Fixed issue when open direction wasn't reactive.
https://ilevel.atlassian.net/browse/VL-46

VL-46_Fix-datepickers-open-direction_Dmytro-Holdobin

---

src/service.helper/index.js
src/ui.form-input-search/configs/default.config.js
src/ui.form-input-search/index.vue

- Added debounce props to search input
- Added debounce helper to service.helper
>https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-55

VL-55_Add-debounce-to-search-input_Dmytro-Holdobin

---

src/ui.form-date-picker-range/index.vue
src/ui.form-input-money/index.vue

Updated refs exposed by UInput component

VL_Fix-input-refs_Dmytro-Holdobin

---

src/ui.data-table/index.vue

Added attrs to table body checkbox

VL_Fix-table-body-checkbox-binding_Dmytro-Holdobin

---

src/ui.form-input-file/index.stories.js
src/ui.form-input-money/index.stories.js
src/ui.form-input-number/index.stories.js
src/ui.form-input-rating/index.stories.js
src/ui.form-input-search/index.stories.js
src/ui.form-input/index.stories.js
src/ui.form-textarea/index.stories.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-42

VL-42_Inputs-stories-code-optimization_Vitalii-Dudnik

---

src/ui.button-link/index.stories.js
src/ui.button-toggle-item/index.stories.js
src/ui.button-toggle/index.stories.js
src/ui.button/index.stories.js
src/ui.container-card/index.stories.js
src/ui.dropdown-button/index.stories.js
src/ui.form-checkbox-group/index.stories.js
src/ui.form-checkbox-multi-state/index.stories.js
src/ui.form-checkbox/index.stories.js
src/ui.form-color-picker/index.stories.js
src/ui.form-date-picker/index.stories.js
src/ui.form-input-file/index.stories.js
src/ui.form-input-money/index.stories.js
src/ui.form-input-number/index.stories.js
src/ui.form-input-rating/index.stories.js
src/ui.form-input-search/index.stories.js
src/ui.form-input/index.stories.js
src/ui.form-label/index.stories.js
src/ui.form-radio-group/index.stories.js
src/ui.form-select/index.stories.js
src/ui.form-switch/index.stories.js
src/ui.form-textarea/index.stories.js
src/ui.image-icon/index.stories.js
src/ui.navigation-pagination/index.stories.js
src/ui.navigation-progress/index.stories.js
src/ui.navigation-tabs/index.stories.js
src/ui.text-badge/index.stories.js
src/ui.text-block/index.stories.js
src/ui.text-empty/index.stories.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-42

VL-42_Checkbox-stories-code-optimization_Vitalii-Dudnik

---

src/composable.ui/index.js
src/ui.button-link/composables/attrs.composable.js
src/ui.button-toggle-item/composables/attrs.composable.js
src/ui.button-toggle/composables/attrs.composable.js
src/ui.button/composables/attrs.composable.js

VL-47_Buttons-&-links-composables-refactoring_Vitalii-Dudnik

---

src/composable.autoPosition/index.js
src/ui.form-date-picker-range/configs/default.config.js
src/ui.form-date-picker/configs/default.config.js

- Fixed datepickers auto position styles
- Fixed autoPosition comoosable misprints

VL_Fix-datepickers-auto-poistion_Dmytro-Holdobin

---

src/ui.dropdown-badge/composables/attrs.composable.js
src/ui.dropdown-button/composables/attrs.composable.js
src/ui.dropdown-link/composables/attrs.composable.js
src/ui.dropdown-list/composables/attrs.composable.js

VL-47_Dropdowns-composables-refactoring_Vitalii-Dudnik

---

src/ui.text-alert/composables/attrs.composable.js
src/ui.text-badge/composables/attrs.composable.js
src/ui.text-block/composables/attrs.composable.js
src/ui.text-empty/composables/attrs.composable.js
src/ui.text-file/composables/attrs.composable.js
src/ui.text-file/index.stories.js
src/ui.text-files/composables/attrs.composable.js
src/ui.text-files/index.stories.js
src/ui.text-header/composables/attrs.composable.js
src/ui.text-money/composables/attrs.composable.js
src/ui.text-notify/composables/attrs.composable.js
src/ui.text-notify/index.stories.js

VL-47_Text-&-content-composables-refactoring_Vitalii-Dudnik

---

src/ui.container-accordion/composables/attrs.composable.js
src/ui.container-card/composable/attrs.composable.js
src/ui.container-col/composables/attrs.composable.js
src/ui.container-divider/composables/attrs.composable.js
src/ui.container-group/composables/attrs.composable.js
src/ui.container-modal-confirm/composable/attrs.composable.js
src/ui.container-modal/composables/attrs.composable.js
src/ui.container-page/composables/attrs.composable.js
src/ui.container-row/composables/attrs.composable.js

VL-47_Containers-composables-refactoring_Vitalii-Dudnik

---

src/composable.ui/index.js
src/constants/index.js
src/service.ui/index.js
src/ui.data-list/composables/attrs.composable.js
src/ui.data-table/composables/attrs.composable.js
src/ui.image-avatar/composables/attrs.composable.js
src/ui.image-icon/composables/attrs.composable.js
src/ui.loader-rendering/composables/attrs.composable.js
src/ui.loader-top/composables/attrs.composable.js
src/ui.loader/composables/attrs.composable.js
src/ui.navigation-pagination/composables/attrs.composable.js
src/ui.navigation-progress/composables/attrs.composable.js
src/ui.navigation-progress/index.stories.js
src/ui.navigation-progress/index.vue
src/ui.navigation-tab/composables/attrs.composable.js
src/ui.navigation-tabs/composables/attrs.composable.js
src/ui.other-dot/composables/attrs.composable.js
src/ui.other-dot/index.stories.js

VL-47_Data-&-other_composables-refactoring_Vitalii-Dudnik

---

src/service.ui/index.js
src/ui.container-page/composables/attrs.composable.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-51

VL-51_Add-es-lint-no-console-for service.ui-color-checks_Vitalii-Dudnik

---

src/ui.text-badge/configs/default.config.js
src/ui.text-badge/index.stories.js
src/ui.text-badge/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-56

VL-56_UBadge-icon-props_Vitalii-Dudnik

---

src/ui.form-date-picker-range/index.stories.js
src/ui.form-date-picker-range/index.vue
src/ui.form-date-picker/index.stories.js
src/ui.form-date-picker/index.vue
src/ui.form-input-money/index.stories.js
src/ui.form-input-money/index.vue
src/ui.form-input-search/index.stories.js
src/ui.form-input-search/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-61

VL-61_Add-icon-props-for-UInput-containing-components_Vitalii-Dudnik

---

src/ui.form-textarea/configs/default.config.js
src/ui.form-textarea/index.stories.js
src/ui.form-textarea/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-71

VL-71_UTextarea-improvements_Vitalii-Dudnik

---

src/ui.container-accordion/configs/default.config.js
src/ui.container-accordion/index.vue
src/ui.dropdown-badge/configs/default.config.js
src/ui.dropdown-badge/index.vue
src/ui.dropdown-button/configs/default.config.js
src/ui.dropdown-button/index.vue
src/ui.dropdown-link/configs/default.config.js
src/ui.dropdown-link/index.vue
src/ui.form-checkbox/configs/default.config.js
src/ui.form-checkbox/index.vue
src/ui.form-switch/configs/default.config.js
src/ui.form-switch/index.vue
src/ui.image-avatar/configs/default.config.js
src/ui.image-avatar/index.vue
src/ui.text-file/configs/default.config.js
src/ui.text-file/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-68

VL-68_Default-icons-config-refactoring_Vitalii-Dudnik

---

src/ui.form-calendar/composables/attrs.composable.js
src/ui.form-calendar/configs/default.config.js
src/ui.form-calendar/constants/index.js
src/ui.form-calendar/index.vue
src/ui.form-date-picker/configs/default.config.js
src/ui.form-date-picker/index.stories.js
src/ui.form-date-picker/index.vue

- Added seconds to timepicker in UCalendar component
- Removed manual time formatting, now you have to use userFormat
> https://ilevel.atlassian.net/browse/VL-66

VL-66_Add-seconds-to-timepicker_Dmytro-Holdobin

---

package.json
src/ui.data-table/components/TableRow.vue
src/ui.data-table/index.vue

> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-77

VL-77_Row-keys-sorting_Dmytro-Holdobin

---

src/ui.loader/index.vue

https://ilevel.atlassian.net/jira/software/c/projects/FN/boards/2?selectedIssue=FN-1866

FN-1866_ULoader-add-default-slot_Vitalii-Dudnik

---

src/ui.data-table/index.vue

Fixed issue when columns not presented in headers were deleted in sorting process

VL_Fix-issue-when-unsed-columns-were-deleted-in-table_Dmytro-Holdobin

---

src/ui.dropdown-list/configs/default.config.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-65

VL-65_UDropdownList-fix-letter-cutting_Vitalii-Dudnik

---

src/ui.form-input-search/configs/default.config.js
src/ui.form-input-search/index.stories.js
src/ui.form-input-search/index.vue

Added min length props to Search input component

VL_Add-min-length-to-search-input_Dmytro-Holdobin

---

src/ui.button/index.vue

Added number type to tabindex props

VL_Add-number-type-to-tabindex-props_Dmytro-Holdobin

---

src/ui.form-calendar/index.vue

Fixed issue when initial time value was not set in calendar timepicker inputs

VL_Fix-datepicker-initial-time_Dmytro-Holdobin

---

.eslintrc.cjs
src/ui.dropdown-list/composables/attrs.composable.js
src/ui.dropdown-list/index.vue
src/ui.form-select/index.stories.js
src/ui.form-select/index.vue

Optimized dropdown list rendering

VL-70_Fix-dropdown-list-refomance-with-large-lists_Dmytro-Holdobin

---

src/ui.data-table/components/TableRow.vue

Fixed inital title for table cells

VL_Fix-initial-table-cell-title_Dmytro_Holdobin

---

src/ui.dropdown-list/index.vue

Fixed issue when dropdown empty item wasn't visible.
> https://ilevel.atlassian.net/browse/VL-75

VL-75_Fix-dropdown-empty-item_Dmytro-Holdobin

---

src/composables/useMutationObserver.js
src/ui.form-input/UInput.vue
src/ui.form-input/storybook/stories.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-87

VL-87_UInput-icon-&-rounding_Vitalii-Dudnik

---

src/ui.dropdown-badge/UDropdownBadge.vue
src/ui.dropdown-badge/storybook/stories.js
src/ui.dropdown-list/UDropdownList.vue

Fixed dropdown errors and keys navigation
> https://ilevel.atlassian.net/browse/VL-82

VL-82_Fix-dropdown-onTab-errors_Dmytro-Holdobin

---

src/ui.data-table/storybook/stories.js

Fixed table component stories
> https://ilevel.atlassian.net/browse/VL-91

VL-91_Fix-talbe-stories_Dmytro-Holdobin

---

src/ui.form-date-picker-range/config.js
src/ui.form-date-picker-range/storybook/stories.js
src/ui.form-date-picker-range/useAttrs.js
src/ui.form-date-picker/config.js
src/ui.form-date-picker/storybook/stories.js
src/ui.form-date-picker/useAttrs.js

Fixed position in datepicker stories. Fixed position of datepicker with description and error
> https://ilevel.atlassian.net/browse/VL-89

VL-81_Fix-datepicker-stories_Dmytro-Holdobin

---

src/ui.form-input-money/UInputMoney.vue

Use newly created elementId instead of props.id

VL_Fix-UInputMoney-elementId_Vitalii-Dudnik

---

src/directives/vClickOutside.js

Fixed v-on-clickoutside for mobile devices

VL_Fix-v-on-clickoutside-directive-for-mobile_Dmytro-Holdobin

---

src/ui.dropdown-list/UDropdownList.vue
src/ui.dropdown-list/storybook/stories.js

Added onClick callback to dropdown list options

VL_Add-on-click-callback-to-dropdown-options_Dmytro-Holdobin

---

src/ui.dropdown-list/UDropdownList.vue

Fix UDropdownList (remove option.onClick)

VL_Fix-UDropdownList_Vitalii-Dudnik

---

src/ui.button-toggle-item/UToggleItem.vue

Fixed multiple select of toggle component

VL_Fix-toggle-multiple-select_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue

- Fixed error in select;
- Fixed wrong Change event implementation;
> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-102

VL-102_Fix-wrong-Change-event-implementation_Dmytro-Holdobin

---

src/ui.text-alert/useAttrs.js
src/ui.text-badge/useAttrs.js
src/ui.text-block/useAttrs.js
src/ui.text-empty/useAttrs.js
src/ui.text-file/UFile.vue
src/ui.text-file/config.js
src/ui.text-file/useAttrs.js
src/ui.text-files/useAttrs.js
src/ui.text-header/useAttrs.js
src/ui.text-money/useAttrs.js
src/ui.text-notify/useAttrs.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-100

VL-100_Text-&-Content-useAttrs-refactoring_Vitalii-Dudnik

---

src/ui.loader-rendering/useAttrs.js
src/ui.loader-top/useAttrs.js
src/ui.loader/ULoader.vue
src/ui.loader/useAttrs.js
src/ui.navigation-pagination/useAttrs.js
src/ui.navigation-progress/UProgress.vue
src/ui.navigation-progress/useAttrs.js
src/ui.navigation-tab/UTab.vue
src/ui.navigation-tab/config.js
src/ui.navigation-tab/useAttrs.js
src/ui.navigation-tabs/useAttrs.js
src/ui.other-dot/useAttrs.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-100

VL-100_Navigation-&-Loaders-useAttrs-refactoring_Vitalii-Dudnik

---

src/ui.form-calendar/useAttrs.js
src/ui.form-checkbox-group/useAttrs.js
src/ui.form-checkbox/useAttrs.js
src/ui.form-color-picker/useAttrs.js
src/ui.form-select/useAttrs.js
src/ui.form-switch/useAttrs.js
src/ui.form-textarea/useAttrs.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-100

VL-100_Datepickers-&-Checkbox-useAttrs-refactoring_Vitalii-Dudnik

---

src/ui.form-date-picker-range/useAttrs.js
src/ui.form-date-picker/useAttrs.js

Refactored datepickers i18n merge watcher

VL_Refactor-datepickers-i18n-merge_Dmytro-Holdobin

---

src/ui.form-input-search/UInputSearch.vue
src/ui.form-select/USelect.vue
src/utils/utilHelper.js

Fixed debounce method
> https://ilevel.atlassian.net/browse/VL-55

VL-44_Fix-debounce-method_Dmytro-Holdobin

---

src/ui.form-checkbox-multi-state/useAttrs.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-100

VL-100_UCheckboxMultiState-useAttrs-refactoring_Vitalii-Dudnik

---

src/ui.container-modal/UModal.vue
src/ui.form-input-search/UInputSearch.vue
src/ui.form-select/USelect.vue

- Added input template ref to UInputSearch component.
- Fixed select groups.
- Fixed issue when UModal rendered empty div with closeOnCross="false"

VL-Small-fixes_Dmytro-Holdobin

---

package-lock.json
package.json

VL_Update-plugin-vite_Dmtyro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

Adjust getRowAttrs, so that class property of a row can be a function

VL_UTable-class-property-adjustment_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendarMonthView.vue
src/ui.form-calendar/UCalendarYearView.vue
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/config.js
src/ui.form-date-picker/config.js

- Fixed datepicker's input focus state.
- Fixed DatepickerRange range input styles.
- Fixed styles related to calendar dates.
> https://ilevel.atlassian.net/browse/VL-93

VL-29_Datepicker-fixes_Dmtyro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js
src/ui.data-table/storybook/Docs.mdx
src/ui.data-table/storybook/stories.js

- Small UI fixes.
- Refactored and fixed date divider.
- Added stories and docs.
> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-94

VL-94_UTable-fixes-and-refactoring_Dmtyro-Holdobin

---

src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js
src/ui.data-table/storybook/Docs.mdx
src/ui.data-table/storybook/stories.js

- Removed primary and secondary keys from Row object.
- Added content key to Row object.
> https://ilevel.atlassian.net/browse/VL-109

VL-109_Remove-primary-secondary-row-logic-from-table_Dmtyro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js
src/ui.data-table/storybook/stories.js
src/ui.data-table/useAttrs.js
src/ui.data-table/utilTable.js

- It's possible to pass cell props to nested rows now.
- Prevented onClickRow event when toggle row visibility icon clicked.
- Added warning when row does not have unique id.

VL_UTable-row-inprovments_Dmtyro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

Added clickCell event tot table component

VL_UTable-add-click-cell-event_Dmtyro-Holdobin

---

src/ui.data-table/UTableRow.vue

Fixed row visibility toggle icon

VL_UTable-fix-row-visibility-toggle-icon_Dmtyro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

Fixed issue when custom styles passed to row object were inherited by nested rows

VL_UTable-custom-row-styles-inheritance_Dmtyro-Holdobin

---

src/ui.data-table/UTableRow.vue

Add class attribute to nested row ("tr" tag)

VL_UTable-nested-row-class-apply_Vitalii-Dudnik

---

docs/customization/components.md
src/ui.text-money/UMoney.vue
src/ui.text-money/config.js
src/ui.text-money/utilMoney.js

Fix decimalPlaces in utilMoney function

VL_UMoney-decimalSeparator-fix_Vitalii-Dudnik

---

.storybook/preview.js
src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js
src/ui.data-table/storybook/stories.js

> https://ilevel.atlassian.net/browse/VL-94
> https://ilevel.atlassian.net/browse/VL-96

VL-94_Table-bugs-and-overflow-props_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/config.js
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/config.js
src/ui.form-date-picker-range/useUserFormat.js
src/ui.form-date-picker/UDatePicker.vue

> https://ilevel.atlassian.net/browse/VL-108
> https://ilevel.atlassian.net/browse/VL-107

VL-108_Add-datepicker-range-date-fromat-props_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/utilTable.js

Add computed prop for checking column.isHidden property

VL_UTable-columns-isHidden_Vitalii-Dudnik

---

src/ui.button-link/ULink.vue
src/ui.button/UButton.vue
src/ui.data-table/UTable.vue
src/ui.dropdown-list/UDropdownList.vue
src/ui.form-calendar/UCalendar.vue
src/ui.form-date-picker/UDatePicker.vue
src/ui.form-input-money/UInputMoney.vue
src/ui.form-input-search/UInputSearch.vue
src/ui.form-label/ULabel.vue
src/ui.form-select/USelect.vue
src/ui.form-textarea/UTextarea.vue
src/ui.text-badge/UBadge.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-111

VL-111_Document-all-expose_Vitalii-Dudnik

---

src/ui.form-date-picker/UDatePicker.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-113

VL-113_Slot-props-improvements_Vitalii-Dudnik

---

docs/customization/icons.md
src/ui.form-input-file/UInputFile.vue
src/ui.form-input-file/config.js
src/ui.text-file/UFile.vue
src/ui.text-file/config.js
src/ui.text-files/UFiles.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-69

VL-69_UFile-delete-button_Vitalii-Dudnik

---

src/ui.loader-progress/ULoaderProgress.vue
src/ui.loader-progress/config.js

Addded loading props do loader progress
> https://ilevel.atlassian.net/browse/VL-79

VL-79_Add-loading-props-to-loader-progress_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/storybook/stories.js
src/ui.data-table/utilTable.js

Table adds id to row if necessary
> https://ilevel.atlassian.net/browse/VL-116

VL-120_Generate-id-for-table-rows_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.js

- Replaced table resource props with loading props
> https://ilevel.atlassian.net/browse/VL-110

VL-110_Remove-table-resource-props_Dmytro-Holdobin

---

src/constants.js
src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-117

VL-117_UTable-empty-cell-props_Vitalii-Dudnik

---

.storybook/preview.js
src/ui.form-input-money/utilFormat.js

- Fixed issue with id in storybook when preview story had same id as default one.
- Fixed money input formatting with big integers.
> https://ilevel.atlassian.net/browse/VL-120

VL-120_Fix-money-input-bugs_Dmytro-Holdobin

---

src/directives/clickOutside/storybook/Docs.mdx
src/directives/clickOutside/storybook/stories.js
src/directives/clickOutside/vClickOutside.js
src/directives/index.js
src/directives/tooltip/storybook/Docs.mdx
src/directives/tooltip/storybook/stories.js
src/directives/tooltip/vTooltip.js
src/ui.dropdown-badge/UDropdownBadge.vue
src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-link/UDropdownLink.vue
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.image-icon/UIcon.vue

Added stories for directives
> https://ilevel.atlassian.net/browse/VL-48

VL-48_Document-directives_Dmytro-Holdobin

---

src/ui.form-input-number/UInputNumber.vue
src/ui.form-input-number/config.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-105

VL-105_UInputNumber-wrap-into-ULabel_Vitalii-Dudnik

---

src/constants.js
src/preset.tailwind.js
src/utils/utilTheme.js
src/utils/utilUI.js
vueless.config.js

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-118

VL-118_Dynamic-ring-offset-color_Vitalii-Dudnik

---

src/ui.image-icon/UIcon.vue

Fixed icon paths in nuxt context
> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-114

VL-114_Fix-icon-in-nuxt-context_Dmytro-Holdobin

---

src/directivesTs/clickOutside/storybook/Docs.mdx
src/directivesTs/clickOutside/storybook/stories.ts
src/directivesTs/clickOutside/types.ts
src/directivesTs/clickOutside/vClickOutside.ts
src/directivesTs/index.ts
src/directivesTs/tooltip/storybook/Docs.mdx
src/directivesTs/tooltip/storybook/stories.ts
src/directivesTs/tooltip/types.ts
src/directivesTs/tooltip/vTooltip.ts
src/types.ts

> https://ilevel.atlassian.net/browse/VL-126

VL-126_Diractives-ts-migration_Dmytro-Holdobin

---

src/ui.form-date-picker/UDatePicker.vue

Removed formatted date from datepicker input event

VL-108_Remove-formatted-date-from-datepicker-input-event

---

src/constants.ts
src/utils/utilMergeConfigs.ts
src/utils/utilUI.ts
src/vite/utils/tailwindSafelist.js

Moved merge config function into separate service
> https://ilevel.atlassian.net/browse/VL-137

VL-137_Decompose-mergeConfig-function_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue
src/ui.data-table/config.js
src/ui.data-table/storybook/stories.js

- Fixed custom date label story
- Adjusted nested row margin
- Fixed sticky actions header

VL-134_Date-table-bug-fixes_Dmytro-Holdobin

---

src/composables/useUI.ts
src/utils/node/mergeConfigs.js
src/utils/node/tailwindSafelist.js
src/utils/ui.ts

Moved getMergedConfig function to separate service
> https://ilevel.atlassian.net/browse/VL-137

VL-137_Move-getMergedConfig-to-separate-file_Dmytro-Holdobin

---

src/ui.form-date-picker-range/UDatePickerRange.vue

Fixed issue when calendar closes immediately after opening

VL_Fix-issue-when-datepicker-closed-after-opening_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue

- Fixed issue when provided initidal value was not visible

VL_Fix-date-picker-initial-value_Dmytro-Holdobin

---

.storybook/preview.js
src/composables/useDarkMode.ts
src/utils/theme.ts

Added useDarkMode composable to track dark mode state reactivly
> https://ilevel.atlassian.net/browse/VL-144

VL-144_Add-use-dark-mode-composable_Dmytro-Holdobin

---

src/ui.form-date-picker-range/UDatePickerRange.vue

Fixed datepicker range next and prev button

VL_Fix-datepicker-range-next-prev-buttons_Dmytro-Holdobin

---

src/ui.form-date-picker/UDatePicker.vue

VL_Fix-datepicker_refs_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendarMonthView.vue
src/ui.form-calendar/UCalendarYearView.vue

Fixed datepicker month and year styles

VL-146_Fix-datepickers-date-styles_Dmytro-Holdobin

---

src/ui.text-money/UMoney.vue
src/ui.text-money/config.ts

VL_Fix-money-sizes_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue

Fixed issue when action header had wrong position
> https://ilevel.atlassian.net/browse/VL-149

VL-149_Fixed-issue-with-stickty-action-header-position_Dmytro-Holdobin

---

.storybook/decorators/storyDarkModeDecorator.js
.storybook/preview.js
src/utils/theme.ts

Fixed issues with storybook dark mode

VL_Fix-issue-when-story-book-switch-should-be-clicke-twice_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/utilTable.ts

- Fixed issue with recursion when item updated from outside of component.
- Refactored code.
- Removed redundant variable from template.

VL_Fix-table-recursion-issue-Holdobin

---

src/ui.data-table/UTable.vue

Fixed table sticky header's cell width
> https://ilevel.atlassian.net/browse/VL-150

VL-150_Fix-table-sticky-header-cell-width_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

Add double-click event for UTable row

VL_UTable-double-click-row_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue

onClickCell returns cell key now

VL_Add-key-to-onClickCell-emit_Dmytro-Holdobin

---

src/ui.dropdown-list/config.ts

Fixed selected option styles of select
> https://ilevel.atlassian.net/browse/VL-151

VL-151_Fix-select-selected-highlight_Dmytro-Holdobin

---

src/directives/clickOutside/storybook/stories.ts
src/directives/tooltip/storybook/stories.ts

Fixed and improved directive stories

VL-48_Fix-directive-stories_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue
src/ui.data-table/config.ts

Adjusted table paddings for nested rows

VL-134_Ajust-table-paddings_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/config.ts
src/ui.form-calendar/constants.ts
src/ui.form-calendar/useAttrs.ts
src/ui.form-calendar/utilCalendar.ts
src/ui.form-calendar/utilFormatting.ts
src/ui.form-date-picker-range/useAttrs.ts
src/ui.form-date-picker-range/useLocale.ts
src/ui.form-date-picker/UDatePicker.vue
src/ui.form-date-picker/config.ts
src/ui.form-input/UInput.vue
tsconfig.vitest.json

- Added ability to copy and paste value to datepicker's input.
- Fixed issue when initial date was not set.
- Fixed issue when parseDate returned wrong month.
- Used vOnClickOutside in datepicker component.
- Minor refactoring and changes.
> https://ilevel.atlassian.net/browse/VL-152

VL-152_Datepicker-fixes-and-improvments_Dmytro-Holdobin

---

package.json

VL_Version-fix_Vitalii-Dudnik

---

src/ui.form-date-picker/UDatePicker.vue

Fixed datepicker input update on paste

VL_Fix-datepicker-input-update-on-paste_Dmytro-Holdobin

---

src/ui.form-date-picker/UDatePicker.vue
src/ui.form-date-picker/storybook/stories.ts

Added ability to copy time format date into datepicker with regular format and vise versa

VL_Add-cross-format-copy-paste-to-datepicker_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue
src/ui.form-calendar/utilCalendar.ts
src/ui.form-calendar/utilFormatting.ts
src/ui.form-date-picker/UDatePicker.vue
src/ui.form-input/UInput.vue

Fixed issue with datepicker when relative day locale is not provided and fixed some bugs after merge

VL_Fix-datepicker-issues_Dmytro-Holdobin

---

src/ui.data-table/UTableRow.vue

Fix text select for double click event

VL_Table-double-click-selection-fix_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/utilCalendar.ts
src/ui.form-date-picker/UDatePicker.vue

Fixed datepicker issue when value was formatted with from format. Fixed issue when time inputs value remains the same after paste

VL_Fix-datepicker-paste-issue-with-custom-date-fromat_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-date-picker/UDatePicker.vue

Rewritten timepicker in UCalendar component. Added auto focus on next field and fixed issue with validation

VL-152_Remake-datepickers-timepicker-logic_Dmytro-Holdobin

---

src/ui.form-color-picker/UColorPicker.vue
src/ui.form-color-picker/types.ts

VL_UColorPicker-TS-fix_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendar.vue

Fixed timepicker's fiels focus delay

VL_Datepicker-time-focus-delay_Dmytro-Holdobin

---

src/ui.button/UButton.vue
src/ui.text-money/config.ts

- Fixed issue when invisible div in button was always rendered.
- Fixed 4xl size of UMoney component.

VL_Small-fixes_Dmytro-Holdobin

---

src/ui.form-date-picker-range/useUserFormat.ts

Fixed issue when wrong locale was used for user format

VL_Fix-datepciker-user-format-locale_Dmytro-Holdobin

---

src/ui.form-date-picker/UDatePicker.vue

VL_Fix-misprint-in-datepicker_Dmytro-Holdobin

---

src/ui.form-calendar/config.ts
src/ui.form-select/config.ts

Fix keys in UCalendar & USelect

VL_UCalendar-&-USelect-config-fix_Vitalii-Dudnik

---

src/ui.form-select/config.ts

Fix styles for correct USelect height

VL_USelect-height-fix_Vitalii-Dudnik

---

src/ui.form-select/config.ts

Fixed select after caret slot styles

VL_Fix-select-after-caret-styles_Dmytro-Holdobin

---

src/composables/useMutationObserver.ts
src/ui.data-table/UTableRow.vue

Fixed recursion  in table row component and improved types

VL_Fix-recursion-in-table-row-and-improve-types_Dmytro-Holdobin

---

src/ui.dropdown-list/UDropdownList.vue

Add padding calculations to dropdown list option for accurate height measurement

VL_UDropdownList-height-fix_Vitalii-Dudnik

---

src/ui.form-input-money/useFormatCurrency.ts
src/ui.form-input-money/utilFormat.ts

Fixed issue when space or minus in input was replaced with NaN
> https://ilevel.atlassian.net/browse/VL-164

VL-164_Fix-input-money-NaN-issue_Dmytro-Holdobin

---

src/ui.data-table/config.ts

Fixed table rows expand icon styles

VL-171_Fix-table-nested-rows-expand-icon-styles_Dmytro-Holdobin

---

package-lock.json
package.json
src/ui.dropdown-list/UDropdownList.vue
src/ui.dropdown-list/types.ts

Remvoed defineModel macro from DropdownList

FN-163_Remove-defineModel-macro-from-dropdownList_Dmytro-Holdobin

---

src/ui.dropdown-list/UDropdownList.vue
src/ui.dropdown-list/config.ts

Remain selected option in dropdown list with the same color on hover as for the active state

VL_USelect-selected-option-hover_Vitalii-Dudnik

---

src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/storybook/stories.ts
src/ui.form-date-picker/UDatePicker.vue
src/ui.form-date-picker/storybook/stories.ts
src/ui.form-input-money/UInputMoney.vue
src/ui.form-input-money/storybook/stories.ts
src/ui.form-input-search/UInputSearch.vue
src/ui.form-input-search/config.ts
src/ui.form-input-search/storybook/stories.ts
src/ui.form-input/UInput.vue
src/ui.form-input/config.ts
src/ui.form-input/storybook/stories.ts
src/ui.form-select/USelect.vue
src/ui.form-select/config.ts
src/ui.form-select/storybook/stories.ts

https://ilevel.atlassian.net/browse/VL-165

VL-165_Remove-icon-slots_Dmytro-Holdobin

---

src/ui.button-toggle-item/config.ts

Fixed safelist color for toggle item
> https://ilevel.atlassian.net/browse/VL-173

VL-137_Fix-toggle-item-saflist-color_Dmytro-Holdobin

---

src/directives/clickOutside/storybook/stories.ts
src/directives/tooltip/storybook/stories.ts

VL-48_Improve-directive-stories_Dmytro-Holdobin

---

src/ui.form-textarea/UTextarea.vue
src/ui.form-textarea/config.ts

Moved UTextarea slots inside input

VL-127_Move-textarea-slots-inside_Dmytro-Holdobin

---

src/ui.form-input-money/utilFormat.ts

Minuses withing money input value ignored now

VL-164_Ignore-minusus-within-money-input-value_Dmytro-Holdobin

---

src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-link/UDropdownLink.vue
src/ui.dropdown-list/types.ts

Fixed issue when dropdown element wasnt closed after select with keyb…oard
> https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-170

VL-170_Fix-dropdown-button-keydown-events_Dmytro-Holdobin

---

src/ui.form-input-search/UInputSearch.vue

Add watchEffect for syncing localValue to modelValue changes

VL_Sync-UInputSearch-localValue-to-modelValue_Vitalii-Dudnik

---

src/ui.form-textarea/UTextarea.vue
src/ui.form-textarea/config.ts

Fixed UTextare paddings
> https://ilevel.atlassian.net/browse/VL-172

VL-172_Fix-textarea-paddings_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue
src/ui.form-select/config.ts
src/ui.form-select/storybook/stories.ts

> https://ilevel.atlassian.net/browse/VL-179
Selects after caret slow always visible now

VL-179_Make-select-after-caret-slot-always-visible_Dmytro-Holdobin

---

src/ui.form-label/ULabel.vue
src/ui.form-textarea/UTextarea.vue

Fixed issue when label was positioned incorrectly

VL_Fix-label-position_Dmytro-Holdobin

---

src/composables/useUI.ts
src/ui.button-toggle-item/config.ts
src/utils/node/tailwindSafelist.js

Fixed nested component dynamic color classes

VL-173_Fix-nested-component-dynamic-colors_Dmytro-Holdobin

---

src/ui.form-input/UInput.vue
src/ui.form-textarea/UTextarea.vue

Fixed input label position after slot changed
> https://ilevel.atlassian.net/browse/VL-172

VL-172_Fix-label-position-on-slot-content-change_Dmytro-Holdobin

---

src/utils/node/tailwindSafelist.js

Changed colors props name for colorpicker
> https://ilevel.atlassian.net/browse/VL-154

VL-154_Fix-nested-component-dynamic-colors_Dmytro-Holdobin

---

src/ui.text-money/UMoney.vue
src/ui.text-money/config.ts
src/ui.text-money/storybook/stories.ts
src/ui.text-money/types.ts
src/ui.text-money/utilMoney.ts

1. Add new prop "unsigned"
2. Rename "default" prop to "auto"
3. Adjust "auto" prop behavior: 
- if value is positive no sign is shown
- if it is negative then minus appears
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-181

VL-181_UMoney-sign-fix_Vitalii-Dudnik

---

bin/commands/index.js
bin/commands/init.js
bin/constants.js
bin/index.js
package-lock.json
package.json

Added init vueless cli command

VL-34_Add-init-cli-command_Dmytro-Holdobin

---

src/ui.form-date-picker/UDatePicker.vue
src/ui.form-date-picker/storybook/stories.ts
src/ui.form-date-picker/types.ts
src/utils/node/dynamicProps.js

Allowed to redefine prop types without @extendOnly keyword
> https://ilevel.atlassian.net/browse/VL-176

VL-176_Allow-to-redefine-prop-types_Dmytro-Holdobin

---

src/constants.js
src/types.ts
src/ui.text-badge/storybook/stories.ts
src/ui.text-empty/storybook/stories.ts
src/ui.text-file/storybook/stories.ts
src/ui.text-files/storybook/stories.ts
src/ui.text-money/UMoney.vue
src/ui.text-money/config.ts
src/ui.text-money/storybook/stories.ts
src/ui.text-money/types.ts
src/ui.text-notify/storybook/stories.ts
src/ui.text-number/UNumber.vue
src/ui.text-number/config.ts
src/ui.text-number/constants.ts
src/ui.text-number/storybook/docs.mdx
src/ui.text-number/storybook/stories.ts
src/ui.text-number/types.ts
src/ui.text-number/utilNumber.ts

Add new "UNumber" component, simplify UMoney
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-182

VL-182_UNumber-new-component_Vitalii-Dudnik

---

src/ui.button-link/storybook/stories.ts
src/ui.button-toggle/storybook/stories.ts
src/ui.dropdown-badge/UDropdownBadge.vue
src/ui.dropdown-badge/config.ts
src/ui.dropdown-badge/storybook/stories.ts
src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-button/storybook/stories.ts
src/ui.dropdown-link/UDropdownLink.vue
src/ui.dropdown-link/config.ts
src/ui.dropdown-link/storybook/stories.ts

Update stories of Dropdown group components

VL-133_UDropdownBadge-&-UDropdownLink-stories-refinement_Vitalii-Dudnik

---

src/ui.form-date-picker-range/UDatePickerRangePeriodMenu.vue

Fix date update bug via key attribute modifying

VL_UDatePickerRange-period-button-fix_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts

Changed table date divider color within selected rows

VL_Change-table-divider-color-within-selected-rows_Dmytro-Holdobin

---

src/ui.form-date-picker-range/config.ts
src/ui.form-date-picker-range/useUserFormat.ts

Fixed issue when not user format locale was used for formatting and fixed input's style

VL-184_Fix-datepicker-range-formatting-bug_Dmytro-Holdobin

---

src/ui.text-number/utilNumber.ts

Add half-dash sign instead of regular hyphen for "minus" sign (UNumber & UMoney components)
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-181
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-182

VL-181-182_UNumber-&-UMoney-minus-sign-fix_Vitalii-Dudnik

---

src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker/UDatePicker.vue

Fixed issue when calendar in datepickers had used default locale when custom was provided

VL_Fix-datepickers-locales_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue

Fixed issue when selected rows werent updated when modal value changed

VL_Fix-table-selected-rows-sync-issue_Dmytro-Holdobin

---

src/ui.form-input-rating/storybook/stories.ts
src/ui.form-input-search/storybook/stories.ts
src/ui.form-input/storybook/stories.ts
src/ui.form-textarea/UTextarea.vue
src/ui.form-textarea/storybook/stories.ts
src/ui.form-textarea/types.ts

Adjust input components' stories, update UTextarea stories

VL-133_UTextarea-stories-refinement_Vitalii-Dudnik

---

src/ui.button-toggle-item/UToggleItem.vue
src/ui.dropdown-list/storybook/docs.mdx
src/ui.form-select/USelect.vue
src/ui.form-select/config.ts
src/ui.form-select/storybook/docs.mdx
src/ui.form-select/storybook/stories.ts
src/ui.form-select/types.ts

Refine USelect component stories

VL-133_USelect-stories-refinement_Vitalii-Dudnik

---

src/ui.form-select/USelect.vue
src/ui.form-select/config.ts

Fix left icon layout in USelect component

VL_USelect-left-icon-layout-fix_Vitalii-Dudnik

---

src/ui.form-input-money/utilFormat.ts

Fixed money input big int issue
> https://ilevel.atlassian.net/browse/VL-187

VL-187_Fix-money-input-big-int-issue_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts

Fixed table date divider positon within dates and styles

VL_Fix-table-date-divider_Dmytro-Holdobin

---

src/ui.image-icon/UIcon.vue

VL_Fix-icons-getIcon-mehtod_Dmytro-Holdobin

---

src/ui.form-input-money/storybook/stories.ts
src/ui.form-input-search/storybook/stories.ts
src/ui.form-input/storybook/stories.ts
src/ui.form-select/storybook/stories.ts
src/ui.form-textarea/storybook/stories.ts

Remove errorMessage computed (now it's possible again to set "error" prop explicitly via global args of a component's default story)
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-189

VL-189_Error-props-args-section-bug_Vitalii-Dudnik

---

src/ui.form-calendar/config.ts
src/ui.form-calendar/utilFormatting.ts
src/ui.form-date-picker-range/config.ts
src/ui.form-date-picker/UDatePicker.vue
src/ui.form-date-picker/config.ts

Added weekdays to relative r key in format function

VL_Add-weekdays-to-r-format-key_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts

Fixed progress loader position for table sticky header

VL_Fix-progress-loader-position-for-table-sticky-header_Dmytro-Holdobin

---

src/ui.form-input-money/utilFormat.ts

VL-201_Fix-money-input-dot-separator_Dmytro-Holdobin

---

src/ui.container-modal-confirm/UModalConfirm.vue
src/ui.container-modal-confirm/config.ts
src/ui.container-modal-confirm/types.ts
src/ui.container-modal/config.ts
src/ui.container-modal/types.ts

Update divider prop docs, add this prop to UModalConfirm

VL_UModalConfirm-divider-prop-add_Vitalii-Dudnik

---

src/ui.form-input-money/utilFormat.ts

Fixed issue when it was impossible to write cents

VL_Fix-money-input-cents_Dmytro-Holdobin

---

src/ui.form-input-money/UInputMoney.vue
src/ui.form-input-money/types.ts
src/ui.form-input-money/useFormatCurrency.ts
src/ui.form-input-money/utilFormat.ts

Rewritten moneyInput format logic

VL_Rewrite-money-input-format-logic_Dmytro-Holdobin

---

src/ui.form-input-money/UInputMoney.vue
src/ui.form-input-money/useFormatCurrency.ts

VL_Money-input-hotfixes_Dmytro-Holdobin

---

src/ui.form-checkbox-group/storybook/stories.ts
src/ui.form-label/config.ts
src/ui.form-label/storybook/stories.ts
src/ui.form-radio-group/storybook/stories.ts
src/ui.form-radio/storybook/stories.ts
src/ui.form-switch/config.ts
src/ui.form-switch/storybook/stories.ts

Refine radio and label components' stories

VL-133_URadio-stories-refinement_Vitalii-Dudnik

---

src/ui.form-input-file/UInputFile.vue
src/ui.form-input-file/config.ts

VL_InputFile-error-fix_Dmytro-Holdobin

---

src/ui.form-label/config.ts

Rollback styles for ULabel's "topInside" align

VL_ULabel-align-styles-fix_Vitalii-Dudnik

---

src/ui.form-input-money/types.ts
src/ui.form-input-money/useFormatCurrency.ts

Fixed money input cursor position

VL_Fix-money-input-cursor_Dmytro-Holdobin

---

src/ui.form-input-money/useFormatCurrency.ts

Fix issue when it was impossible to write cents

VL_Fix-input-money-cents-issue_Dmytro-Holdobin

---

src/directives/tooltip/vTooltip.ts

Fixed reactivity loss on tippy options update

VL-205_Fix-tippy-directive-reactivity-loss_Dmytro-Holdobin

---

src/bin/commands/copy.js

Fixed copy component ENOENT error

VL-175_Fix-copy-component-ENOENT-error_Dmytro-Holdobin

---

src/bin/commands/init.js
src/bin/index.js

Improved errors styling and added vueless config backup on init command

VL-34_Add-vueless-config-back-up-on-init_Dmytro-Holdobin

---

src/ui.data-table/config.ts
src/ui.data-table/storybook/stories.ts

Added margin fro first table divider and improved docs

VL_Add-table-divider-margin-and-improve-docs_Dmytro-Holdobin

---

src/ui.container-accordion/storybook/stories.ts
src/ui.container-card/UCard.vue
src/ui.container-card/config.ts
src/ui.container-card/storybook/stories.ts
src/ui.container-col/storybook/stories.ts
src/ui.container-divider/storybook/stories.ts
src/ui.container-divider/types.ts
src/ui.container-group/UGroup.vue
src/ui.container-group/storybook/stories.ts
src/ui.container-groups/storybook/stories.ts
src/ui.container-modal-confirm/UModalConfirm.vue
src/ui.container-modal-confirm/storybook/stories.ts
src/ui.container-modal-confirm/types.ts
src/ui.container-modal/UModal.vue
src/ui.container-modal/config.ts
src/ui.container-modal/storybook/stories.ts
src/ui.container-modal/types.ts
src/ui.container-page/UPage.vue
src/ui.container-page/storybook/stories.ts
src/ui.container-row/storybook/stories.ts
src/ui.container-row/types.ts

Refine stories for Containers components' group

VL-133_Containers-group-stories-refinement_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts
src/ui.data-table/storybook/stories.ts

VL-133_UTable-stories-refinement_Vitalii-Dudnik

---

src/ui.container-card/UCard.vue

Update isShownHeader computed with new slots' names in UCard component

VL_UCard-slots-names-computed-update_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/types.ts
src/ui.data-table/utilTable.ts

Fixed issue when all rows were re-rendered when only one was checked

VL-204_Fix-row-rerender_Dmytro-Holdobin

---

src/ui.form-calendar/storybook/stories.ts
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/UDatePickerRangePeriodMenu.vue
src/ui.form-date-picker-range/config.ts
src/ui.form-date-picker-range/storybook/stories.ts
src/ui.form-date-picker-range/types.ts
src/ui.form-date-picker/storybook/stories.ts
src/ui.form-date-picker/types.ts

Refine stories of all datepicker components

VL-133_Datepickers-stories-refinement_Vitalii-Dudnik

---

src/ui.loader-overlay/storybook/stories.ts
src/ui.loader-progress/storybook/stories.ts
src/ui.loader/storybook/stories.ts

Refine stories of Loaders group

VL-133_Loaders-group-stories-refinement_Vitalii-Dudnik

---

src/ui.form-input-file/UInputFile.vue
src/ui.form-input-file/storybook/stories.ts
src/ui.text-file/UFile.vue
src/ui.text-file/types.ts
src/ui.text-files/UFiles.vue

Refine UInputFile stories, update UFile slots' docs

VL-133_UInputFile-stories-refinement_Vitalii-Dudnik

---

src/ui.container-divider/config.ts
src/ui.data-table/config.ts

Fixed issue when divider's label was not relative to divider

VL_Fix-issue-with-table-divider-position_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/types.ts
src/ui.data-table/utilTable.ts

- Fixed table nesting.
- Removed reclusive rendering from table row.

VL_Fix-table-nesting_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/types.ts
src/ui.data-table/utilTable.ts

Renamed internal parent id key in table

VL_Rename-table-inner-parent-id-key_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts

Fix sticky header position, move "absolute" class from div to config for correct implementation

VL_UTable-stickyHeader-position-fix_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendarDayView.vue

Remove variant="soft" from first- and lastDayInRange buttons for correct UI styles

VL_UCalendar-first-&-last-dayInRange-button-variant-fix_Vitalii-Dudnik

---

src/ui.container-card/UCard.vue

Add defineExpose to the UCard wrapper so users can reference it externally

VL_UCard-wrapperRef-expose_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/storybook/stories.ts
src/ui.data-table/types.ts
src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/storybook/stories.ts
src/ui.form-calendar/types.ts
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/storybook/stories.ts
src/ui.form-date-picker-range/types.ts
src/ui.form-date-picker-range/useLocale.ts
src/ui.form-input-number/UInputNumber.vue
src/ui.form-input-number/storybook/stories.ts
src/ui.form-input-number/types.ts
src/ui.image-avatar/UAvatar.vue
src/ui.image-avatar/storybook/stories.ts
src/ui.image-avatar/types.ts
src/ui.navigation-progress/UProgress.vue
src/ui.navigation-progress/storybook/stories.ts
src/ui.navigation-progress/types.ts

VL_Fix-props-interface-names_Dmytro-Holdobin

---

src/utils/theme.ts

Small bug fixes for setTheme / setColorMode functions

VL_setTheme-small-fixes_Vitalii-Dudnik

---

src/utils/theme.ts

VL_setTheme-rounding-fix_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/UTableRow.vue
src/ui.data-table/storybook/docs.mdx
src/ui.data-table/storybook/stories.ts
src/ui.data-table/types.ts
src/ui.data-table/utilTable.ts
src/utils/helper.ts

- Added v-model values for selected and expanded rows.
- Removed isChecked, isShown and nestedData keys from rows.
- Replaced nestedContent slot with nestedRow slot.
- Moved date divider to table component.

VL_Table-improvements_Dmytro-Holdobin

---

src/ui.button/UButton.vue

Fix invisible div inside UButton to not show v-text

VL_UButton-invisible-div-fix_Vitalii-Dudnik

---

src/ui.form-textarea/UTextarea.vue
src/ui.form-textarea/types.ts

Add maxLength prop for UTextarea component

VL_UTextarea-maxLength-prop_Vitalii-Dudnik

---

src/ui.form-input-rating/UInputRating.vue

Fix hover state when rating is unselected.
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-193

VL-193_UInputRating-refactoring_Vitalii-Dudnik

---

src/ui.container-modal/UModal.vue
src/ui.container-modal/config.ts

-  Restricted focus by tab button outside UModal.
-  Replaced close icon wrapper with a button to make it focusable.
> https://ilevel.atlassian.net/browse/VL-228

VL-228_Restrict-focus-via-tab-button-outside-UModal_Dmytro-Holdobin

---

src/ui.form-listbox/UListbox.vue

Fixed issue when pointer doesn't highlight option

VL_Fix-listbox-hightlight-pointer-styles_Dmytro-Holdobin

---

src/ui.container-modal/UModal.vue

https://ilevel.atlassian.net/browse/VL-229

VL_Fix-modal-scroll_Dmytro-Holdobin

---

src/ui.form-color-picker/UColorPicker.vue
src/ui.form-color-picker/config.ts

Set defaults values from config for UColorpicker props

VL_Set-defaults-from-config-for-UColorPicker_Dmytro-Holdobin

---

src/ui.data-table/UTable.vue
src/ui.data-table/config.ts
src/ui.data-table/storybook/stories.ts

Fix before-header slot rounding

VL_UTable-before-header-slot-rounding_Vitalii-Dudnik

---

.storybook/index.css
src/ui.button/storybook/stories.ts
src/ui.other-dot/storybook/stories.ts
src/ui.other-theme-color-toggle/storybook/stories.ts
src/ui.text-alert/storybook/stories.ts
src/ui.text-badge/storybook/stories.ts
src/ui.text-block/storybook/stories.ts
src/ui.text-empty/storybook/stories.ts
src/ui.text-file/storybook/stories.ts
src/ui.text-files/storybook/stories.ts
src/ui.text-header/storybook/stories.ts
src/ui.text-notify/config.ts
src/ui.text-number/storybook/stories.ts

Refine Text&Content group stories

VL-226_Refine-Text-&-Content-group-stories_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendarDayView.vue

Added preview for selected range in UCalendar

Added preview for selected range in UCalendar

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/UCalendarDayView.vue

> https://ilevel.atlassian.net/browse/VL-237

VL-237_Focus-new-date-range-date-in-view_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue
src/ui.form-select/config.ts

Fix placeholder display for multiple labels

VL_USelect-placeholder-fix_Vitalii-Dudnik

---

src/ui.form-listbox/UListbox.vue
src/ui.form-select/USelect.vue
src/ui.form-select/config.ts
src/ui.form-select/constants.ts
src/ui.form-select/types.ts

Add native "title" prop to listbox option, implement "tags" multipleVariant for USelect component.

VL_USelect-tags-multipleVariant_Vitalii-Dudnik

---

src/ui.form-checkbox-group/storybook/stories.ts
src/ui.form-checkbox-multi-state/storybook/stories.ts
src/ui.form-checkbox/storybook/stories.ts
src/ui.form-color-picker/storybook/stories.ts
src/ui.form-date-picker-range/storybook/stories.ts
src/ui.form-date-picker/storybook/stories.ts
src/ui.form-input-counter/storybook/stories.ts
src/ui.form-input-file/config.ts
src/ui.form-input-file/storybook/stories.ts
src/ui.form-input-number/storybook/stories.ts
src/ui.form-input-password/storybook/stories.ts
src/ui.form-input-rating/storybook/stories.ts
src/ui.form-input-search/storybook/stories.ts
src/ui.form-input/storybook/stories.ts
src/ui.form-label/storybook/stories.ts
src/ui.form-listbox/storybook/stories.ts
src/ui.form-radio-group/storybook/stories.ts
src/ui.form-radio/storybook/stories.ts
src/ui.form-select/storybook/stories.ts
src/ui.form-switch/storybook/stories.ts
src/ui.form-textarea/storybook/stories.ts
src/ui.text-files/storybook/stories.ts

Refine Enum templates for Input group stories

VL-226_Input-group-stories-refinement_Vitalii-Dudnik

---

src/ui.form-calendar/utilDate.ts
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/UDatePickerRangePeriodMenu.vue
src/ui.form-date-picker-range/storybook/stories.ts

- Fixed days validation.
- Used min and max date when they are within the selected period.
> https://ilevel.atlassian.net/browse/VL-240

VL-240_DatepickerRang-date-limiting_Dmytro-Holdobin

---

src/plugin-vite.js

Added vueless directives to optimizeDeps
> https://ilevel.atlassian.net/browse/VL-230

VL-230_Fix-dependency-optimization-reload_Dmytro-Holdobin

---

src/ui.button/storybook/stories.ts
src/ui.dropdown-badge/storybook/stories.ts
src/ui.dropdown-button/storybook/stories.ts
src/ui.dropdown-link/storybook/stories.ts
src/ui.form-checkbox-group/UCheckboxGroup.vue
src/ui.form-checkbox-group/storybook/stories.ts
src/ui.form-checkbox/storybook/stories.ts
src/ui.form-date-picker/storybook/stories.ts
src/ui.form-input/config.ts
src/ui.form-input/storybook/stories.ts
src/ui.form-label/config.ts
src/ui.form-label/storybook/stories.ts
src/ui.form-listbox/storybook/stories.ts
src/ui.form-radio-group/storybook/stories.ts
src/ui.form-radio/storybook/stories.ts
src/ui.form-select/config.ts
src/ui.form-select/storybook/stories.ts
src/ui.form-switch/storybook/stories.ts
src/ui.form-textarea/config.ts
src/ui.form-textarea/storybook/stories.ts
src/ui.other-chip/storybook/stories.ts

- Refine stories for form&inputs group components
- Fix USelect width for left/right

VL_Form-group-stories-refinement_Vitalii-Dudnik

---

src/ui.container-accordion/storybook/stories.ts
src/ui.container-col/config.ts
src/ui.container-col/storybook/stories.ts
src/ui.container-divider/storybook/stories.ts
src/ui.container-group/storybook/stories.ts
src/ui.container-groups/storybook/stories.ts
src/ui.container-row/storybook/stories.ts

Refine stories for Container group

VL_Containers-group-stories-refinement_Vitalii-Dudnik

---

src/ui.form-listbox/UListbox.vue
src/ui.form-listbox/config.ts

Enhance UListbox component: adjust input height calculation and update padding and border styles for improved layout.
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-251

VL-251_UListbox-search-field-fixed-position_Vitalii-Dudnik

---

src/ui.image-icon/UIcon.vue
src/ui.image-icon/tests/UIcon.test.ts

Fixed and refactored UIcon component tests

VL_Refactor-UIcon-tests_Dmytro-Holdobin

---

src/ui.form-switch/tests/USwitch.test.ts

Refactored and improved tests for USwitch component

VL-253_Refactor-USwitch-tests_Dmytro-Holdobin

---

src/ui.form-checkbox/tests/UCheckbox.test.ts
src/ui.form-checkbox/types.ts

Refactored and improved tests for UCheckbox component

VL-253_Refactor-UCheckbox-tests_Dmytro-Holdobin

---

src/ui.form-input-counter/UInputCounter.vue
src/ui.form-input-counter/tests/UInputCounter.test.ts
src/ui.form-input-file/UInputFile.vue
src/ui.form-input-file/tests/UInputFile.test.ts
src/ui.form-input-number/UInputNumber.vue
src/ui.form-input-number/tests/UInputNumber.test.ts
src/ui.form-input-number/useFormatNumber.ts
src/ui.form-input-password/tests/UInputPassword.test.ts
src/ui.form-input-rating/UInputRating.vue
src/ui.form-input-rating/tests/UInputRating.test.ts
src/ui.form-input-search/tests/UInputSearch.test.ts
src/ui.form-input/UInput.vue
src/ui.form-input/tests/UInput.test.ts
src/ui.form-label/ULabel.vue
src/ui.form-label/config.ts
src/ui.form-label/storybook/stories.ts
src/ui.form-label/tests/ULabel.test.ts
src/ui.form-label/types.ts
src/ui.form-radio/URadio.vue
src/ui.form-select/USelect.vue
src/ui.form-switch/USwitch.vue
src/ui.form-textarea/UTextarea.vue
src/ui.form-textarea/tests/UTextarea.test.ts
src/ui.form-textarea/types.ts
src/ui.image-icon/UIcon.vue
src/ui.image-icon/config.ts
src/ui.image-icon/tests/UIcon.test.ts
test/setup.ts

- UInput (`ui.form-input`) 
- UInputCounter (`ui.form-input-counter`) 
- UInputFile (`ui.form-input-file`)
- UInputNumber (`ui.form-input-number`) 
- UInputPassword (`ui.form-input-password`) 
- UInputRating (`ui.form-input-rating`) 
- UInputSearch (`ui.form-input-search`)
- UTextarea (`ui.form-textarea`) 
- ULabel (`ui.form-label`)

Unit tests for input-* components

---

src/ui.form-checkbox/UCheckbox.vue
src/ui.form-checkbox/config.ts

Add partiallyChecked & partiallyCheckedIcon keys to UCheckbox config

VL_UCheckbox-partiallySelected-key_Vitalii-Dudnik

---

src/ui.form-listbox/UListbox.vue
src/ui.form-listbox/tests/UListbox.test.ts

https://ilevel.atlassian.net/browse/VL-258

VL-258_UListbox-tests_Dmytro-Holdobin

---

src/ui.form-select/USelect.vue
src/ui.form-select/tests/USelect.test.ts

VL-258_Add-USelect-tests_Dmytro-Holdobin

---

src/ui.form-listbox/UListbox.vue
src/ui.form-listbox/tests/UListbox.test.ts
src/ui.form-select/USelect.vue
src/ui.form-select/tests/USelect.test.ts

- UListbox (`ui.form-listbox`)
- USelect (`ui.form-select`)

Select and listbox

---

src/ui.data-table/config.ts
src/ui.data-table/storybook/docs.mdx
src/ui.data-table/storybook/stories.ts
src/ui.data-table/types.ts

Refine UTable component's stories

VL_UTable-stories-refinement_Vitalii-Dudnik

---

src/ui.data-list/UDataList.vue
src/ui.data-list/config.ts
src/ui.data-list/storybook/docs.mdx
src/ui.data-list/storybook/stories.ts
src/ui.data-list/types.ts
src/ui.data-table/UTableRow.vue
src/ui.data-table/storybook/docs.mdx
src/ui.data-table/storybook/stories.ts
src/ui.data-table/types.ts

Refine UDataList component's stories, update markdown table for UTable meta keys, change "contentClasses" row objet key to "contentClass" for consistency.

VL_UDataList-stories-refinement_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/UCalendarMonthView.vue
src/ui.form-calendar/UCalendarYearView.vue
src/ui.form-calendar/storybook/stories.ts

Refine UCalendar stories, fix viewSwitchButton for correct years range display

VL_UCalendar-stories-refinement_Vitalii-Dudnik

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/UCalendarDayView.vue
src/ui.form-calendar/constants.ts
src/ui.form-date-picker-range/UDatePickerRange.vue
src/ui.form-date-picker-range/UDatePickerRangePeriodMenu.vue
src/ui.form-date-picker-range/storybook/stories.ts
src/ui.form-date-picker-range/types.ts
src/ui.form-date-picker/storybook/stories.ts

- Introduced a new STEP constant in constants.ts for consistent step increments.
- Updated UCalendar.vue to improve date handling logic, ensuring correct date updates in range selection.
- Enhanced UCalendarDayView.vue to track clicks on the same day and reset selection after three clicks.
- Modified UDatePickerRange.vue to handle null values for date ranges more effectively.
- Refined storybook stories for UDatePicker and UDatePickerRange components, improving layout and interaction examples.

VL_UDatePickerRange-stories-refinement_Vitalii-Dudnik

---

src/ui.data-list/tests/UDataList.test.ts

Enhance unit tests for UDataList component: added tests for props, functionality, slots, events, and exposed properties. Improved structure and coverage for better maintainability.

VL-252_Add-UDataList-tests_Dmytro-Holdobin

---

src/ui.form-calendar/UCalendar.vue
src/ui.form-calendar/UCalendarDayView.vue
src/ui.form-calendar/UCalendarMonthView.vue
src/ui.form-calendar/UCalendarYearView.vue
src/ui.form-calendar/types.ts
src/ui.form-calendar/utilCalendar.ts

- Fixed issue when switch label was changed alongside the active date.
- Removed visual styles of active date after navigation with prev and next button
- Refactored calendar component. Removed active month variable in favor of activeDate.

VL_Fix-calendar-year-view-rendering_Dmytro-Holdobin

---

src/ui.data-list/tests/UDataList.test.ts
src/ui.data-table/UTable.vue
src/ui.data-table/tests/UTable.test.ts
src/ui.data-table/tests/UTableRow.test.ts

- UDataList (`ui.data-list`) 
- UDataTable (`ui.data-table`)

Data table and list tests

---

src/ui.container-accordion/UAccordion.vue
src/ui.container-accordion/config.ts
src/ui.container-accordion/storybook/stories.ts
src/ui.data-table/UTable.vue
src/ui.form-listbox/UListbox.vue
src/ui.form-listbox/storybook/stories.ts
src/ui.form-select/config.ts
src/ui.form-select/storybook/stories.ts
src/ui.navigation-pagination/UPagination.vue
src/ui.navigation-pagination/config.ts
src/ui.navigation-pagination/tests/UPagination.test.ts
src/ui.navigation-pagination/types.ts

General improvements:
- Add default slot support in UAccordion
- Fix UListbox title display (use labelKey prop)
- Update pagination configuration to include ellipsis styling and modified variant options

VL_Bugs-fixes_Vitalii-Dudnik

---

src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-button/config.ts
src/ui.dropdown-button/storybook/stories.ts
src/ui.dropdown-button/tests/UDropdownButton.test.ts
src/ui.dropdown-button/types.ts

Add prop `block` to UDropdownButton component

VL_UDropdownButton-block-prop_Vitalii-Dudnik

---

src/ui.container-accordion/UAccordion.vue
src/ui.container-accordion/config.ts
src/ui.container-accordion/storybook/stories.ts
src/ui.container-accordion/tests/UAccordion.test.ts

Enhance UAccordion component functionality:
- Add description prop and default slot rendering condition
- Update related test

VL_UAccordion-default-slot-&-description-render_Vitalii-Dudnik

---

src/utils/theme.ts

Refactor theme utility functions to check both runtime and global `text`/`outline`/`rounding `values

VL_Theme-util-merged-configs-fix_Vitalii-Dudnik

---

src/ui.data-table/UTable.vue
src/ui.data-table/storybook/stories.ts
src/ui.data-table/tests/UTable.test.ts

Add new "header-counter" slot to the UTable component

VL_UTable-header-counter-slot_Vitalii-Dudnik

---

src/directives/tooltip/storybook/docs.mdx
src/directives/tooltip/storybook/stories.ts
src/directives/tooltip/vTooltip.ts
src/tailwind.css

Refactor vTooltip directive:
- Enhance the directive with light and dark theme support;
- Update styles and documentation;
- The tooltip will dynamically adapt to the current theme;
- Update storybook examples to reflect these changes.

VL_VTooltip-directive-refactoring_Vitalii-Dudnik

---

package-lock.json
src/ui.form-input-password/UInputPassword.vue
src/ui.form-select/USelect.vue

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-265

VL-265_Accessibility-issues_Vitalii-Dudnik

---

src/constants.js
src/index.d.ts
src/index.ts
src/types.ts
src/ui.container-accordion-item/UAccordionItem.vue
src/ui.container-accordion-item/config.ts
src/ui.container-accordion-item/constants.ts
src/ui.container-accordion-item/storybook/docs.mdx
src/ui.container-accordion-item/storybook/stories.ts
src/ui.container-accordion-item/tests/UAccordionItem.test.ts
src/ui.container-accordion-item/types.ts
src/ui.container-accordion/UAccordion.vue
src/ui.container-accordion/config.ts
src/ui.container-accordion/storybook/stories.ts
src/ui.container-accordion/tests/UAccordion.test.ts
src/ui.container-accordion/types.ts

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-266

VL-266_UAccordion-new-features_Vitalii-Dudnik

---

src/ui.form-input-counter/UInputCounter.vue
src/ui.form-input-counter/config.ts
src/ui.form-input-counter/tests/UInputCounter.test.ts
src/ui.form-input-counter/types.ts
src/ui.form-input-number/UInputNumber.vue
src/ui.form-input-number/utilFormat.ts
src/ui.form-input-password/UInputPassword.vue
src/ui.form-input/UInput.vue
src/ui.form-listbox/UListbox.vue

Fix: Fix decimal numbers rounding bug

VL_Input-group-enhancements_Vitalii-Dudnik

---

src/constants.js
src/utils/theme.ts

Allow negative values of `letterSpacing` to bet set in cookies

VL_Letter-spacing-negative-value-fix_Vitalii-Dudnik

---

src/constants.js
src/utils/theme.ts

Feat: implement `lightTheme` / `darkTheme` retrieval functions

VL_LightTheme-&-DarkTheme-cookies-set_Vitalii-Dudnik

---

src/ui.dropdown-badge/UDropdownBadge.vue
src/ui.dropdown-button/UDropdownButton.vue
src/ui.dropdown-link/UDropdownLink.vue
src/ui.form-listbox/UListbox.vue
src/ui.form-select/USelect.vue
src/utils/theme.ts

Remove search input clear on option select in UListbox

VL_UListbox-search-clear-fix_Vitalii-Dudnik

---

src/constants.js
src/index.d.ts
src/index.ts
src/types.ts
src/ui.container-drawer/UDrawer.vue
src/ui.container-drawer/config.ts
src/ui.container-drawer/constants.ts
src/ui.container-drawer/storybook/docs.mdx
src/ui.container-drawer/storybook/stories.ts
src/ui.container-drawer/tests/UDrawer.test.ts
src/ui.container-drawer/types.ts

Add new `UDrawer` component.
https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-270

VL-270_UDrawer-component_Vitalii-Dudnik
